```sql
WITH 
INSTOCK AS(
	SELECT FISCAL_YEAR,WEEK_NUMBER_IN_FISCAL_YEAR, STYLE_DISPLAY_NUMBER,SKU_DISPLAY_NUMBER,STORE_NUMBER,AVG(day_instock) as INSTOCK
	FROM
	(
	SELECT FISCAL_YEAR,WEEK_NUMBER_IN_FISCAL_YEAR, STYLE_DISPLAY_NUMBER,SKU_DISPLAY_NUMBER, STORE_NUMBER,
	SUM(CASE WHEN TOTAL_ONHAND > 0 THEN 1 ELSE 0 END)/7  AS DAY_INSTOCK
	FROM
	(
	SELECT FISCAL_YEAR, WEEK_NUMBER_IN_FISCAL_YEAR, DATE_VALUE,PRODUCT_MEMBER_KEY,STYLE_DISPLAY_NUMBER,SKU_DISPLAY_NUMBER,STORE_NUMBER ,ASSORTMENT_STATUS,SUM(HA.ON_HAND_UNITS) AS TOTAL_ONHAND
	FROM EDW_SPOKE..FACT_BPS_HISTORIC_ASSORTMENT HA
	JOIN EDW_SPOKE..DIM_PRODUCT_BPS P
	ON HA.PRODUCT_MEMBER_KEY = P.MEMBER_KEY
	JOIN EDW_SPOKE..DIM_DATE D
	ON D.DATE_VALUE >= HA.START_DATE AND D.date_value <= HA.END_DATE
	RIGHT JOIN EDW_SPOKE..DIM_STORE S
	ON HA.STORE_MEMBER_KEY = S.MEMBER_KEY
	WHERE FISCAL_YEAR >= 2020
	AND date_value <= CURRENT_DATE	
	AND ASSORTMENT_STATUS = 'A'
	GROUP BY 1,2,3,4,5,6,7,8
	ORDER BY 2,1
	) TEMP1
	GROUP BY 1,2,3,4,5
	) TEMP2
	GROUP BY 1,2,3,4,5
	ORDER BY 1,2
	),
SALES AS (
	SELECT SKU_DISPLAY_NUMBER,STYLE_display_number, WEEK_NUMBER_IN_FISCAL_YEAR, FISCAL_YEAR,STORE_NUMBER,AVG(SALES_PRICE) SALE_PRICE  ,SUM( SALE_QUANTITY) TOTAL_SALES
	FROM
	(
	SELECT *  FROM EDW_SPOKE.NZ.FACT_BPS_SALES_DETAIL HA
	JOIN EDW_SPOKE..DIM_PRODUCT_BPS P
	ON HA.INVENTORY_PRODUCT_MEMBER_KEY  = P.MEMBER_KEY
	JOIN EDW_SPOKE..DIM_STORE S
	ON HA.STORE_MEMBER_KEY = S.MEMBER_KEY
	JOIN EDW_SPOKE..DIM_DATE D
	ON D.DATE_VALUE >= HA.PROCESS_DATE  AND D.date_value <= HA.PROCESS_DATE 
	WHERE FISCAL_YEAR >= 2020
	) TEMP1
	WHERE SALE_QUANTITY > 0
	GROUP BY 1,2,3,4,5
	),
PROFILE AS (
	SELECT 
	week,
	(CASE WHEN WEEK > (SELECT EXTRACT(WEEK FROM CURRENT_DATE) ) THEN (SELECT EXTRACT(YEAR FROM CURRENT_DATE))
	ELSE (SELECT EXTRACT(YEAR FROM CURRENT_DATE)+1) 
	END) AS fiscal_year,
	CAST(SKUNBR AS VARCHAR(10)) SKUNBR ,
 	P.style_display_number,
	'ALL' AS STORE,
	0 AS SALE_PRICE,
	WEEKLY_FORECAST,
	0 AS instock, 
	0 AS DOOR_COUNT
	FROM (
	SELECT SKUNBR ,1 AS week,SUM( SFC01) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR 
	UNION ALL 
	SELECT SKUNBR ,2 AS week,SUM( SFC02) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,3 AS week,SUM( SFC03) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,4 AS week,SUM( SFC04) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,5 AS week,SUM( SFC05) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,6 AS week,SUM( SFC06) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,7 AS week,SUM( SFC07) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,8 AS week,SUM( SFC08) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,9 AS week,SUM( SFC09) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,10 AS week,SUM( SFC10) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,11 AS week,SUM( SFC11) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,12 AS week,SUM( SFC12) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,13 AS week,SUM( SFC13) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,14 AS week,SUM( SFC14) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,15 AS week,SUM( SFC15) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,16 AS week,SUM( SFC16) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,17 AS week,SUM( SFC17) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,18 AS week,SUM( SFC18) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,19 AS week,SUM( SFC19) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,20 AS week,SUM( SFC20) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,21 AS week,SUM( SFC21) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,22 AS week,SUM( SFC22) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,23 AS week,SUM( SFC23) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,24 AS week,SUM( SFC24) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,25 AS week,SUM( SFC25) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,26 AS week,SUM( SFC26) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,27 AS week,SUM( SFC27) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,28 AS week,SUM( SFC28) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,29 AS week,SUM( SFC29) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,30 AS week,SUM( SFC30) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,31 AS week,SUM( SFC31) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,32 AS week,SUM( SFC32) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,33 AS week,SUM( SFC33) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,34 AS week,SUM( SFC34) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,35 AS week,SUM( SFC35) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,36 AS week,SUM( SFC36) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,37 AS week,SUM( SFC37) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,38 AS week,SUM( SFC38) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,39 AS week,SUM( SFC39) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,40 AS week,SUM( SFC40) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,41 AS week,SUM( SFC41) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,42 AS week,SUM( SFC42) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,43 AS week,SUM( SFC43) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,44 AS week,SUM( SFC44) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,45 AS week,SUM( SFC45) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,46 AS week,SUM( SFC46) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,47 AS week,SUM( SFC47) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,48 AS week,SUM( SFC48) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,49 AS week,SUM( SFC49) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,50 AS week,SUM( SFC50) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,51 AS week,SUM( SFC51) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	UNION ALL 
	SELECT SKUNBR ,52 AS week,SUM( SFC52) weekly_forecast FROM EDW_HUB_STAGE.NZ.CURRENT_SALES_BPS_FUT_MRSRQW1P  GROUP BY SKUNBR
	) TEMP1
	LEFT JOIN EDW_SPOKE..DIM_PRODUCT_BPS  P
	ON p.sku_display_number = temp1.skunbr
	WHERE MEMBER_type = 'BPS PRODUCT'
	ORDER BY WEEK),
ASSORTMENT AS (
	SELECT FISCAL_YEAR, WEEK_NUMBER_IN_FISCAL_YEAr,STYLE_DISPLAY_NUMBER,SKU_DISPLAY_NUMBER,
	COUNT(DISTINCT store_number) assorted_store_count
	FROM EDW_SPOKE..FACT_BPS_HISTORIC_ASSORTMENT HA
	JOIN EDW_SPOKE..DIM_PRODUCT_BPS P
	ON HA.PRODUCT_MEMBER_KEY = P.MEMBER_KEY
	JOIN EDW_SPOKE..DIM_DATE D
	ON D.DATE_VALUE >= HA.START_DATE AND D.date_value <= HA.END_DATE
	RIGHT JOIN EDW_SPOKE..DIM_STORE S
	ON HA.STORE_MEMBER_KEY = S.MEMBER_KEY
	WHERE FISCAL_YEAR >= 2020
	AND date_value <= CURRENT_DATE
	AND S.CHANNEL_GROUP = 'RETAIL'
	AND ASSORTMENT_STATUS = 'A'
	GROUP BY 1,2,3,4
	ORDER BY 1,2
	)
SELECT * FROM 
(
(SELECT s.week_number_in_fiscal_year,s.FISCAL_YEAR ,s.SKU_DISPLAY_NUMBER, s.STYLE_DISPLAY_NUMBER, s.STORE_NUMBER,AVG(SALE_PRICE) AS AVG_SALE_PRICE ,SUM( TOTAL_SALES) SALES_UNIT, AVG(INSTOCK) INSTOCK,AVG(assorted_store_count) 
FROM sales s
LEFT JOIN instock i 
ON  I.SKU_DISPLAY_NUMBER = S.SKU_DISPLAY_NUMBER 
AND I.FISCAL_YEAR = S.FISCAL_YEAR
AND I.WEEK_NUMBER_IN_FISCAL_YEAR = S.WEEK_NUMBER_IN_FISCAL_YEAR
AND I.STORE_NUMBER = S.STORE_NUMBER
LEFT JOIN ASSORTMENT A
ON  I.SKU_DISPLAY_NUMBER = A.SKU_DISPLAY_NUMBER
AND I.FISCAL_YEAR = A.FISCAL_YEAR
AND I.WEEK_NUMBER_IN_FISCAL_YEAR = A.WEEK_NUMBER_IN_FISCAL_YEAR
GROUP BY 1,2,3,4,5
ORDER BY S.FISCAL_YEAR
, S.week_number_in_fiscal_year, store_number)
UNION ALL 
(SELECT * FROM profile)
) temp5
WHERE sku_display_number in (3420403,3420404,3420405,3420406,3420412,3420413,3420414,3420415
)
ORDER BY FISCAL_YEAR ,week_number_in_fiscal_year,STORE_NUMBER, SKU_DISPLAY_NUMBER

















